name: CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change this to your project version if needed

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --junitxml=report.xml  # If you use pytest
        # Or use `python -m unittest discover` if you’re using unittest

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.xml
